# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  job-id:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/triangulum-ctv/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'triangulumadmin@triangulum-ctv.iam.gserviceaccount.com'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
  
    - name: Checkout
      uses: actions/checkout@v2


