name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      # We must run the actions/checkout@v3. Omitting the checkout step or putting it after auth will cause future steps to be unable to authenticate.
      uses: actions/checkout@v3

    - name: Setup GCP Service Account
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        
    - name: 'Use gcloud CLI'
      run: 'gcloud info'
